"""Drum kits: one style prompt -> a full kit of one-shots with round robins.

Every piece is generated by Stable Audio 3 Small SFX with the same style words, on the
General MIDI drum map (kick C1, snare D1, closed hat F#1...), so the kit plays from any
DAW's drum editor. Written as a Decent Sampler preset (round robins, open hat choked by
the closed hat) and an SFZ (one_shot, seq_length, group/off_by), like an instrument.
"""

import re
from dataclasses import dataclass, field
from pathlib import Path
from xml.sax.saxutils import quoteattr

import numpy as np

from .audio import ExportFormat, write_wav
from .instruments import midi_to_name

KITS_DIR = "Kits"
MAX_ROUND_ROBINS = 4
PREVIEW_GAP_S = 0.12
PREVIEW_PIECE_S = 0.7


@dataclass(frozen=True)
class Piece:
    key: str
    words: str
    midi: int
    seconds: float
    choke: str = ""        # this piece's choke group ("hat")
    choked_by: str = ""    # silenced when a piece of this group plays


PIECES = (
    Piece("kick", "kick drum", 36, 0.9),
    Piece("rim", "rimshot", 37, 0.5),
    Piece("snare", "snare drum", 38, 0.9),
    Piece("clap", "hand clap", 39, 0.8),
    Piece("closed-hat", "closed hi-hat", 42, 0.4, choke="hat"),
    Piece("low-tom", "low tom drum", 45, 1.2),
    Piece("open-hat", "open hi-hat", 46, 1.5, choke="ohat", choked_by="hat"),
    Piece("mid-tom", "mid tom drum", 47, 1.1),
    Piece("crash", "crash cymbal", 49, 3.0),
    Piece("high-tom", "high tom drum", 50, 1.0),
    Piece("ride", "ride cymbal", 51, 2.5),
    Piece("perc", "percussion hit", 56, 0.8),
)


@dataclass(frozen=True)
class KitRequest:
    prompt: str               # the kit's style, e.g. "dusty 90s boom bap, vinyl"
    name: str = ""
    round_robins: int = 3
    seed: int | None = None
    export: ExportFormat = field(default_factory=lambda: ExportFormat(bit_depth="24"))
    model: str = "sa3-sfx"
    mode: str = "kit"
    uses_source = False  # class attribute, not a field: kits never transform a source

    @property
    def variations(self) -> int:  # for the job list: takes per piece
        return self.round_robins

    def full_prompt(self) -> str:
        return f"Drum kit: {self.prompt.strip()}"

    def piece_prompt(self, piece: Piece) -> str:
        return f"{self.prompt.strip()}, {piece.words} one-shot, single hit, drum sample"

    def title(self) -> str:
        return re.sub(r"\s+", " ", self.name or f"{self.prompt} kit").strip()[:80]

    def validate(self, source_seconds=None) -> None:
        if not self.prompt.strip():
            raise ValueError("Describe the kit's style, e.g. “dusty 90s boom bap” or “hard techno, distorted”.")
        if len(self.prompt) > 400:
            raise ValueError("Keep the style under 400 characters.")
        if not 1 <= self.round_robins <= MAX_ROUND_ROBINS:
            raise ValueError(f"Round robins: 1 to {MAX_ROUND_ROBINS} takes per piece.")
        if self.seed is not None and not 0 <= self.seed <= 2**32 - 1:
            raise ValueError("Seed is out of range.")


def sample_path(piece: Piece, take: int) -> str:
    return f"Samples/{piece.key}_{take}_{midi_to_name(piece.midi).replace('#', 's')}.wav"


def kit_preset(title: str, takes: dict[str, list[str]]) -> str:
    groups = []
    for piece in PIECES:
        paths = takes.get(piece.key, [])
        if not paths:
            continue
        rr = f' seqMode="round_robin" seqLength="{len(paths)}"' if len(paths) > 1 else ""
        mute = (f' tags={quoteattr(piece.choke)}' if piece.choke else "") + (
            f' silencedByTags={quoteattr(piece.choked_by)} silencingMode="fast"' if piece.choked_by else "")
        samples = "\n".join(
            f'        <sample path={quoteattr(path)} rootNote="{piece.midi}" loNote="{piece.midi}" '
            f'hiNote="{piece.midi}" seqPosition="{i}"{mute}/>'
            for i, path in enumerate(paths, start=1))
        groups.append(f'      <group name={quoteattr(piece.key)}{rr}>\n{samples}\n      </group>')
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<DecentSampler minVersion="1.0.0">\n'
        '  <ui width="812" height="375" bgColor="FF141414">\n'
        '    <tab name="main">\n'
        f'      <label x="20" y="10" width="700" height="24" text={quoteattr(title)} textColor="FFFF9A66"/>\n'
        '    </tab>\n'
        '  </ui>\n'
        # Long release: drum hits ring out even when the note is short (one-shot behaviour).
        '  <groups attack="0.0" decay="1" sustain="1" release="8">\n'
        + "\n".join(groups) + "\n"
        '  </groups>\n'
        '</DecentSampler>\n'
    )


def kit_sfz(title: str, takes: dict[str, list[str]]) -> str:
    lines = [f"// {title} (samplegen drum kit, General MIDI map)"]
    chokes = {"hat": 1, "ohat": 2}
    for piece in PIECES:
        paths = takes.get(piece.key, [])
        if not paths:
            continue
        group = f" group={chokes[piece.choke]}" if piece.choke else ""
        off_by = f" off_by={chokes[piece.choked_by]}" if piece.choked_by else ""
        lines.append(f"<group> key={piece.midi} loop_mode=one_shot seq_length={len(paths)}{group}{off_by}")
        lines += [f"<region> sample={path} seq_position={i}" for i, path in enumerate(paths, start=1)]
    return "\n".join(lines) + "\n"


def write_kit(folder: Path, title: str, file_stem: str, takes: dict[str, list[np.ndarray]], sample_rate: int,
              fmt: ExportFormat) -> dict[str, list[str]]:
    """Samples/*.wav + <stem>.dspreset + <stem>.sfz. Returns piece -> relative sample paths."""
    (folder / "Samples").mkdir(parents=True, exist_ok=True)
    paths: dict[str, list[str]] = {}
    for piece in PIECES:
        for take, audio in enumerate(takes.get(piece.key, []), start=1):
            rel = sample_path(piece, take)
            write_wav(folder / rel, audio, sample_rate, fmt, title=f"{title} {piece.words} {take}")
            paths.setdefault(piece.key, []).append(rel)
    (folder / f"{file_stem}.dspreset").write_text(kit_preset(title, paths), encoding="utf-8")
    (folder / f"{file_stem}.sfz").write_text(kit_sfz(title, paths), encoding="utf-8")
    return paths


def kit_preview(takes: dict[str, list[np.ndarray]], sample_rate: int) -> np.ndarray:
    """Each piece once, in kit order, for auditioning in the library."""
    gap = np.zeros((int(PREVIEW_GAP_S * sample_rate), 2))
    parts = []
    for piece in PIECES:
        if takes.get(piece.key):
            parts += [takes[piece.key][0][: int(PREVIEW_PIECE_S * sample_rate)], gap]
    return np.concatenate(parts) if parts else np.zeros((0, 2))
